package psp.proyectos;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;

public class MainFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    public MainFrame() {
        initComponents();
        setIconoVentana();      // método para ponerle el icono a la ventana
        aniadirImagenesABotones();  // Este método lo creanmos nosotros
    }

    private void setIconoVentana() {
        //Busca dentro del classpath (en src/imagenes) el archivo play.png.
        URL url1 = MainFrame.class.getResource("/images/play.png");

        //Crea un objeto ImageIcon con esa imagen
        ImageIcon image1 = new ImageIcon(url1);

        //Cambia el icono del JFrame por esa imagen
        this.setIconImage(image1.getImage());
    }

    private void aniadirImagenesABotones() {

        URL url1 = MainFrame.class.getResource("/images/edge.png");
        ImageIcon image1 = new ImageIcon(url1);
        btnEdge.setIcon(image1);

        URL url2 = MainFrame.class.getResource("/images/netbeans.png");
        ImageIcon image2 = new ImageIcon(url2);
        btnNetbeans.setIcon(image2);

        URL url3 = MainFrame.class.getResource("/images/steam.png");
        ImageIcon image3 = new ImageIcon(url3);
        btnSteam.setIcon(image3);

        URL url4 = MainFrame.class.getResource("/images/cmd.png");
        ImageIcon image4 = new ImageIcon(url4);
        btnConsola.setIcon(image4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdge = new javax.swing.JButton();
        btnNetbeans = new javax.swing.JButton();
        btnSteam = new javax.swing.JButton();
        btnConsola = new javax.swing.JButton();
        txtComando = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        chkRedirigir = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnEjecutarComando = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lanzador de Programas");
        setPreferredSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        btnEdge.setBorderPainted(false);
        btnEdge.setContentAreaFilled(false);
        btnEdge.setFocusPainted(false);
        btnEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdgeActionPerformed(evt);
            }
        });

        btnNetbeans.setBorderPainted(false);
        btnNetbeans.setContentAreaFilled(false);
        btnNetbeans.setFocusPainted(false);
        btnNetbeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetbeansActionPerformed(evt);
            }
        });

        btnSteam.setBorderPainted(false);
        btnSteam.setContentAreaFilled(false);
        btnSteam.setFocusPainted(false);
        btnSteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSteamActionPerformed(evt);
            }
        });

        btnConsola.setBorderPainted(false);
        btnConsola.setContentAreaFilled(false);
        btnConsola.setFocusPainted(false);
        btnConsola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsolaActionPerformed(evt);
            }
        });

        txtComando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComandoActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        chkRedirigir.setText("Redirigir salida a fichero");
        chkRedirigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRedirigirActionPerformed(evt);
            }
        });

        jLabel1.setText("Comando a ejecutar en consola");

        jLabel2.setText("Salida de comandos");

        jLabel3.setText("Microsoft Edge");

        jLabel4.setText("Apache NetBeans");

        jLabel5.setText("Steam");

        jLabel6.setText("Consola");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        btnEjecutarComando.setText("Ejecutar");
        btnEjecutarComando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarComandoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkRedirigir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNetbeans, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnConsola)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(16, 16, 16))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComando, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEjecutarComando)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEdge, btnNetbeans, btnSteam});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNetbeans, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSteam, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsola, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtComando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnEjecutarComando))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(chkRedirigir)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConsola, btnEdge, btnNetbeans, btnSteam});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkRedirigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRedirigirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRedirigirActionPerformed

    //Atributo de tipo dictionary con clave valor donde se va a añadir cada botón
    //clickeado junto con su proceso.Esto se hará dentro de cada evento click
    private Map<JButton, Process> procesosActivos = new HashMap<>();

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        //Recorremos todos los procesos
        for (Map.Entry<JButton, Process> elementoPar : procesosActivos.entrySet()) {

            JButton boton = elementoPar.getKey();
            Process proceso = elementoPar.getValue();

            // Si ya ha terminado, habilitamos su botón
            if (!proceso.isAlive()) {

                boton.setEnabled(true);
            }
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private Process consolaProcess;
    private void btnConsolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsolaActionPerformed
        String comando = "cmd /c start cmd";
        ProcessBuilder b = new ProcessBuilder(comando.split("\\s"));

        try {
            consolaProcess = b.start();
            btnConsola.setEnabled(false);
            procesosActivos.put(btnConsola, consolaProcess);

            //Si el checkBox está seleccionado
            if (chkRedirigir.isSelected()) {

                // 🔹 Guardar en archivo
                PrintWriter pr = new PrintWriter(
                        new BufferedWriter(
                                new OutputStreamWriter(
                                        new FileOutputStream("salida.txt", true),
                                        StandardCharsets.UTF_8)));

                pr.println("✔ Consola lanzada correctamente");
                pr.close();

            } else {

                jTextArea1.append("✔ Consola lanzada correctamente\n");

            }

        } catch (IOException ex) {

            // Hacemos el mismo control del checkBox en el catch
            if (chkRedirigir.isSelected()) {
                try {
                    // 🔹 Guardar en archivo
                    PrintWriter pr = new PrintWriter(
                            new BufferedWriter(
                                    new OutputStreamWriter(
                                            new FileOutputStream("salida.txt", true),
                                            StandardCharsets.UTF_8)));

                    pr.println(ex.getMessage());

                } catch (FileNotFoundException ex1) {

                    jTextArea1.append("❌ ERROR al guardar en salida.txt: " + ex1.getMessage() + "\n");
                }

            } else {
                jTextArea1.append("❌ ERROR: " + ex.getMessage() + "\n");
            }
        }
    }//GEN-LAST:event_btnConsolaActionPerformed

    // Atributo de clase para poder controlar el proceso desde el btnActualizar
    private Process edgeProcess;
    private void btnEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdgeActionPerformed

        String comando = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe";
        ProcessBuilder b = new ProcessBuilder(comando.split("\\s"));
        try {

            // Lanzamos el proceso y lo guardamos en una variable de clase
            edgeProcess = b.start();
            // Desactivamos el botón para evitar múltiples lanzamientos
            btnEdge.setEnabled(false);
            //Añadimos el botón y el proceso al Map
            procesosActivos.put(btnEdge, edgeProcess);

            //Este tipo de aplicación no genera mensaje estandar de consola ni error
            //Por lo tanto el mensaje lo escibimos 
            //Si el checkBox está seleccionado
            if (chkRedirigir.isSelected()) {

                // 🔹 Guardar en archivo
                PrintWriter pr = new PrintWriter(
                        new BufferedWriter(
                                new OutputStreamWriter(
                                        new FileOutputStream("salida.txt", true),
                                        StandardCharsets.UTF_8)));

                pr.println("✔ Microsoft Edge lanzado correctamente");

                pr.close();

            } else {

                jTextArea1.append("✔ Microsoft Edge lanzado correctamente\n");

            }

        } catch (IOException ex) {

            // Hacemos el mismo control del checkBox en el catch
            if (chkRedirigir.isSelected()) {
                try {
                    // 🔹 Guardar en archivo
                    PrintWriter pr = new PrintWriter(
                            new BufferedWriter(
                                    new OutputStreamWriter(
                                            new FileOutputStream("salida.txt", true),
                                            StandardCharsets.UTF_8)));

                    pr.println(ex.getMessage());

                } catch (FileNotFoundException ex1) {

                    jTextArea1.append("❌ ERROR al guardar en salida.txt: " + ex1.getMessage() + "\n");
                }

            } else {
                jTextArea1.append("❌ ERROR: " + ex.getMessage() + "\n");
            }
        }

    }//GEN-LAST:event_btnEdgeActionPerformed

    private Process beansProcess;
    private void btnNetbeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetbeansActionPerformed

        String comando = "C:\\Users\\Nazir\\Desktop\\NetBeans-Portable-27\\netbeans-27-JDK21.bat";
        //como no hay argumentos separados por espacios no se hace el split
        ProcessBuilder b = new ProcessBuilder(comando.split("\\s"));

        try {

            beansProcess = b.start();
            btnNetbeans.setEnabled(false);
            procesosActivos.put(btnNetbeans, beansProcess);

            //Si el checkBox está seleccionado
            if (chkRedirigir.isSelected()) {

                // 🔹 Guardar en archivo
                PrintWriter pr = new PrintWriter(
                        new BufferedWriter(
                                new OutputStreamWriter(
                                        new FileOutputStream("salida.txt", true),
                                        StandardCharsets.UTF_8)));

                pr.println("✔ NetBeans lanzado correctamente");

                pr.close();

            } else {

                jTextArea1.append("✔ NetBeans lanzado correctamente\n");

            }

        } catch (IOException ex) {

            // Hacemos el mismo control del checkBox en el catch
            if (chkRedirigir.isSelected()) {
                try {
                    // 🔹 Guardar en archivo
                    PrintWriter pr = new PrintWriter(
                            new BufferedWriter(
                                    new OutputStreamWriter(
                                            new FileOutputStream("salida.txt", true),
                                            StandardCharsets.UTF_8)));

                    pr.println(ex.getMessage());

                } catch (FileNotFoundException ex1) {

                    jTextArea1.append("❌ ERROR al guardar en salida.txt: " + ex1.getMessage() + "\n");
                }

            } else {

                jTextArea1.append("❌ ERROR: " + ex.getMessage() + "\n");
            }
        }
    }//GEN-LAST:event_btnNetbeansActionPerformed

    Process steamProcess;
    private void btnSteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSteamActionPerformed
        String comando = "C:\\Program Files (x86)\\Steam\\steam.exe";
        ProcessBuilder b = new ProcessBuilder(comando.split("\\s"));

        try {
            steamProcess = b.start();
            btnSteam.setEnabled(false);
            procesosActivos.put(btnSteam, steamProcess);

            //Si el checkBox está seleccionado
            if (chkRedirigir.isSelected()) {

                // 🔹 Guardar en archivo
                PrintWriter pr = new PrintWriter(
                        new BufferedWriter(
                                new OutputStreamWriter(
                                        new FileOutputStream("salida.txt", true),
                                        StandardCharsets.UTF_8)));

                pr.println("✔ Steam lanzado correctamente");
                pr.close();

            } else {

                jTextArea1.append("✔ Steam lanzado correctamente\n");

            }

        } catch (IOException ex) {

            // Hacemos el mismo control del checkBox en el catch
            if (chkRedirigir.isSelected()) {
                try {
                    // 🔹 Guardar en archivo
                    PrintWriter pr = new PrintWriter(
                            new BufferedWriter(
                                    new OutputStreamWriter(
                                            new FileOutputStream("salida.txt", true),
                                            StandardCharsets.UTF_8)));

                    pr.println(ex.getMessage());

                } catch (FileNotFoundException ex1) {

                    jTextArea1.append("❌ ERROR al guardar en salida.txt: " + ex1.getMessage() + "\n");
                }

            } else {
                jTextArea1.append("❌ ERROR: " + ex.getMessage() + "\n");
            }
        }
    }//GEN-LAST:event_btnSteamActionPerformed

    private void txtComandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComandoActionPerformed

    private void btnEjecutarComandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarComandoActionPerformed

        String comando = txtComando.getText();

        if (comando.isEmpty()) {

            jTextArea1.append("Debe de introducir un comando para ejecutar");
        } else {

            String comandoComplet = "cmd /c " + comando;
            ProcessBuilder b = new ProcessBuilder(comandoComplet.split("\\s"));
            try {
                Process p = b.start();

                BufferedReader salida = new BufferedReader(
                        new InputStreamReader(p.getInputStream()));
                BufferedReader error = new BufferedReader(
                        new InputStreamReader(p.getErrorStream()));

                String linea;

                if (chkRedirigir.isSelected()) {

                    PrintWriter pr = new PrintWriter(new BufferedWriter(
                            new OutputStreamWriter(
                                    new FileOutputStream("salida.txt", true), StandardCharsets.UTF_8)));
                    
                    while ((linea = salida.readLine()) != null) {

                        pr.println(linea);

                    }
                    while ((linea = error.readLine()) != null) {

                 

                        pr.println(linea);

                    }
                    pr.close();
                } else {

                    while ((linea = salida.readLine()) != null) {

                        jTextArea1.append(linea + "\n");
                    }
                    while ((linea = error.readLine()) != null) {

                        jTextArea1.append(linea + "\n");
                    }
                }

            } catch (IOException ex) {

                if (chkRedirigir.isSelected()) {
                    try {
                        PrintWriter pr = new PrintWriter(new BufferedWriter(
                                new OutputStreamWriter(
                                        new FileOutputStream("salida.txt", true), StandardCharsets.UTF_8)));

                        pr.println(ex.getMessage());
                        
                        pr.close();
                    } catch (FileNotFoundException ex1) {

                        jTextArea1.append("❌ ERROR al guardar en salida.txt: " + ex1.getMessage() + "\n");
                    }
                } else {

                    jTextArea1.append("❌ ERROR: " + ex.getMessage() + "\n");
                }
            }

        }


    }//GEN-LAST:event_btnEjecutarComandoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsola;
    private javax.swing.JButton btnEdge;
    private javax.swing.JButton btnEjecutarComando;
    private javax.swing.JButton btnNetbeans;
    private javax.swing.JButton btnSteam;
    private javax.swing.JCheckBox chkRedirigir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtComando;
    // End of variables declaration//GEN-END:variables
}
